services:
  iso-creation-mkimage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iso-creation-mkimage
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./iso-builder:/home/iso-builder
      - ./shared-packages:/home/shared-packages
    working_dir: /home
    links: 
      - web-packages
    networks:
      - web-server-network

  web-packages:
    build:
      context: ./custom-packages
      dockerfile: Dockerfile
    volumes:
      - ./shared-packages:/usr/share/nginx/html
    ports:
      - 6060:6060
    networks:
      - web-server-network

networks:
  web-server-network:
    driver: bridge